// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/graph": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/actions": {
    params: {};
  };
  "/actions/:actionId": {
    params: {
      "actionId": string;
    };
  };
  "/new-agent": {
    params: {};
  };
  "/add-action": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/graph" | "/chat" | "/dashboard" | "/actions" | "/actions/:actionId" | "/new-agent" | "/add-action";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/graph.tsx": {
    id: "routes/graph";
    page: "/graph";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/chat" | "/dashboard" | "/actions" | "/actions/:actionId" | "/new-agent" | "/add-action";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/actions.tsx": {
    id: "routes/actions";
    page: "/actions";
  };
  "routes/action-details.tsx": {
    id: "routes/action-details";
    page: "/actions/:actionId";
  };
  "routes/new-agent.tsx": {
    id: "routes/new-agent";
    page: "/new-agent";
  };
  "routes/add-action.tsx": {
    id: "routes/add-action";
    page: "/add-action";
  };
};